name: Edit content request
description: Improve existing content on Tilburg Science Hub
title: "[Edit]: "
labels: ["edit content request"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Describe the problem. Is this a small fix (typos, few sentences...) or does it require more elaborate changes (modifying, adding or removing an entire paragraph or chapter, modifying the content structure...)?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. It's just a small typo on this article [...]
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about your request here.
      placeholder: Drag and drop a screenshot here.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://tilburgsciencehub.com/contribute/code-of-conduct)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
