name: Feature request for research
description: Request research-related help from Tilburg Science Hub
title: "[Feature]: "
labels: ["feature request"]
assignees:
  - octocat
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: Ex. email@example.com
      validations:
      required: false
  - type: textarea
    id: block-tutorial
    attributes:
      label: Would you like this to be a Building Block or a Tutorial?
      description: A clear and concise description of what the format of solution will be.
      placeholder: Ex. I'm always frustrated when [...]
      validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      validations:
      required: true
  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: A clear and concise description of the purpose of this request is.
      validations:
      required: false
  - type: textarea
    id: motivation
    attributes:
        label: Motivation
        description: A clear and concise description of the motivation of this request is.
        placeholder: Drag and drop a screenshot here.
        validations:
        required: false
  - type: textarea
    id: title
    attributes:
          label: Suggested title
          description: The title of this request is.
          placeholder: Drag and drop a screenshot here.
          validations:
          required: true
    - type: textarea
      id: keywords
      attributes:
            label: Suggested keywords
            description: The keywords related to this request
            placeholder: Drag and drop a screenshot here.
          validations:
            required: false
    - type: textarea
      id: tools
      attributes:
            label: Required tools
            description: A clear and concise description of the required tools to solve this request.
            placeholder: Drag and drop a screenshot here.
            validations:
            required: false
    - type: textarea
      id: additional-context
      attributes:
            label: Additional context
            description: Add any other context or screenshots about your request here.
            placeholder: Drag and drop a screenshot here.
            validations:
            required: false
    - type: textarea
      id: references
      attributes:
            label: References
            description: Add the references related to this request
            placeholder: Drag and drop a screenshot here.
            validations:
            required: false
    - type: checkboxes
      id: terms
      attributes:
            label: Code of Conduct
            description: By submitting this issue, you agree to follow our [Code of Conduct](https://tilburgsciencehub.com/contribute/code-of-conduct)
            options:
            - label: I agree to follow this project's Code of Conduct
            required: true
